# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Xgc9qD6x4gHUva443wdzSL3OECSqH0u
"""

import random

class Personaje:
    def __init__(self, nombre, vida, ataque, defensa):
        self.nombre = nombre
        self.vida = vida
        self.ataque = ataque
        self.defensa = defensa

    def atacar(self, enemigo):
        dano = max(0, self.ataque - enemigo.defensa + random.randint(-3, 3))
        enemigo.vida -= dano
        print(f"{self.nombre} ataca a {enemigo.nombre} causando {dano} de daño.")
        if enemigo.vida <= 0:
            print(f"{enemigo.nombre} ha sido derrotado.")

    def estado(self):
        return f"{self.nombre} - Vida: {self.vida}"

class Guerrero(Personaje):
    def __init__(self, nombre):
        super().__init__(nombre, vida=40, ataque=10, defensa=8)

class Mago(Personaje):
    def __init__(self, nombre):
        super().__init__(nombre, vida=25, ataque=15, defensa=5)

jugador = Guerrero("Arthur")
enemigo = Mago("Morgana")

def combate(jugador, enemigo):
    print("¡Comienza la batalla!")
    print(jugador.estado())
    print(enemigo.estado())
    print("---")

    while jugador.vida > 0 and enemigo.vida > 0:
        jugador.atacar(enemigo)
        if enemigo.vida > 0:
            enemigo.atacar(jugador)
        print(jugador.estado())
        print(enemigo.estado())
        print("---")

    if jugador.vida > 0:
        print(f"{jugador.nombre} ha ganado la batalla!")
    else:
        print(f"{enemigo.nombre} ha ganado la batalla!")

combate(jugador, enemigo)

"""# Task
Tell me about this dataset.

Here is all the data you need:
"DatosPFPYEF.xlsx"

## Data loading

### Subtask:
Load the dataset from the "DatosPFPYEF.xlsx" file into a Pandas DataFrame.

**Reasoning**:
The task is to load the dataset into a pandas DataFrame and display the first 5 rows. The instructions provide the specific steps to accomplish this, which are importing pandas, reading the Excel file, storing the data in a DataFrame, and printing the first 5 rows. I will group all these steps into a single code block.

## Data exploration

### Subtask:
Explore and understand the basic characteristics of the loaded dataset.

**Reasoning**:
The instructions require exploring the basic characteristics of the dataset, including shape, head, info, describe, and nunique. These steps are all related to basic data exploration and can be grouped into a single code block for efficiency.

## Data analysis

### Subtask:
Perform a detailed analysis of the dataset to extract meaningful insights.

**Reasoning**:
The current subtask is to perform a detailed analysis of the dataset. This involves calculating descriptive statistics for numerical columns, analyzing categorical columns by calculating value counts, and calculating the mean, median, and standard deviation for 'Precio (USD)', 'Kilometraje', and 'Consumo (km/L)'. I will combine all the instructions in one code block.

**Reasoning**:
The subtask is to create visualizations to better understand the data's distributions and relationships. This involves creating histograms, bar charts, scatter plots, and box plots as per the instructions. I will group all the visualization steps into a single code block to generate all the required plots.

## Summary:

### 1. Q&A

Based on the analysis, here are the answers to potential questions about the dataset:

*   **What is the average price of the cars in the dataset?**
    The average price of the cars is $19,157.68, with a median price of $18,844.
*   **What is the average mileage of the cars?**
    The average mileage of the cars is 76.69, with a median of 79.
*   **What is the average fuel consumption?**
    The average fuel consumption is 12.635 km/L, with a median of 12.8 km/L.
*   **Which car brands are most represented in the dataset?**
    Ford is the most represented brand with 30 cars, followed by Honda (22), Chevrolet (19), Nissan (15), and Toyota (14).
*   **Which car models are most represented in the dataset?**
    Focus and Fiesta are the most represented models, with 9 cars each.
*   **What are the most common types of transmissions?**
    Manual transmission cars (51) are slightly more common than automatic (49).
*   **What are the most common fuel types?**
    Diesel is the most common fuel type (37), followed by Hybrid (35) and Gasoline (28).
* **Is there any relationship between Kilometraje and Precio?**
   Yes, based on the scatter plot, there appears to be a negative correlation between Kilometraje and Precio (USD), meaning that the higher the mileage, the lower the price tends to be.
* **Is there a notable difference between the distribution of Precio (USD) based on the Transmision?**
   Yes, based on the box plot, the distribution of car prices is slightly different based on the transmission type.
* **Is there a notable difference between the distribution of Consumo (km/L) based on the Combustible?**
   Yes, based on the box plot, the distribution of fuel consumption varies by fuel type.

### 2. Data Analysis Key Findings

*   **Dataset Size:** The dataset contains 100 rows and 9 columns.
*   **Numerical Statistics:**
    *   The average car price is $19,157.68, with a standard deviation of $6,410.17.
    *   The average mileage is 76.69, with a standard deviation of 41.91.
    *   The average fuel consumption is 12.635 km/L, with a standard deviation of 2.51.
*   **Categorical Analysis:**
    *   Ford is the most common car brand (30 cars), followed by Honda (22 cars) and Chevrolet (19 cars).
    *   The models Focus and Fiesta are the most common (9 cars each).
    *   There are slightly more manual transmission cars (51) than automatic (49).
    *   Diesel is the most common fuel type (37 cars), followed by Hybrid (35 cars) and Gasoline (28 cars).
* **Relationship between Kilometraje and Precio**:
    * There appears to be a negative correlation between Kilometraje and Precio (USD).
* **Distribution of Precio based on Transmision**:
    * The distribution of car prices is slightly different based on the transmission type.
* **Distribution of Consumo based on Combustible**:
    * The distribution of fuel consumption varies by fuel type.

### 3. Insights or Next Steps

*   **Price-Mileage Relationship:** The negative correlation between mileage and price suggests that higher mileage cars generally have lower prices. Further investigation can be done to quantify this relationship and create a predictive model.
*   **Fuel Efficiency Analysis:** The distribution of fuel consumption by fuel type indicates that some fuel types are more efficient than others. A deeper analysis can be conducted to compare the fuel efficiency across different brands and models.
"""